name: continuous-integration
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [min, 1, nightly]
        os: [ubuntu-latest, macos-latest]
        exclude:
          - os: macos-latest
            version: min
          - os: macos-latest
            version: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Julia Setup
        uses: julia-actions/setup-julia@v2
        with:
            version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
        with:
            cache-compiled: "true"
      - name: Test
        uses: julia-actions/julia-runtest@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage Process
        uses: julia-actions/julia-processcoverage@v1
      - name: Coverage Upload
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
