name: Style-Enforcer
on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # note: keep in sync with `format/run.jl`
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  format-check:
    name: Style Enforcement (Julia ${{ matrix.version }} - ${{ github.event_name }})
    # Run on push's or non-draft PRs
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    # TODO: further restrict this
    permissions: write-all
    strategy:
      matrix:
        version: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Julia Setup
        uses: julia-actions/setup-julia@v2
        with:
            version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
        with:
            cache-compiled: "true"
      - name: Instantiate `format` environment and format
        run: |
          julia --project=@format -e'
          using Pkg;
          Pkg.add("JuliaFormatter")
          using JuliaFormatter
          format(".", YASStyle())'
      - uses: reviewdog/action-suggester@v1
        if: github.event_name == 'pull_request'
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
